product_grid_selector:
  container_class: ProductListing_allProducts__24sl2
  item_class: ProductListing_productItemWrapper__1AXaV
  link_path: .//a[@rel="noopener noreferrer"]

categories:
  roof_tile:
    &roof_tile_default
    name: ProductDescription_displayName__ztjNk
    id: ProductDescription_specText__1SueV
    size: //*[@id="__next"]/div[2]/div[3]/div[1]/div/div[2]/div/div[2]/div[2]/span
    weight: //*[@id="__next"]/div[2]/div[3]/div[1]/div/div[2]/div/div[2]/div[3]/span
    price: ProductPricing_priceAmount__uQ7jS
    unit: ProductPricing_priceUnit__1Ki0S

  translucent:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9A
      %E0%B8%B7%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B9%82
      %E0%B8%9B%E0%B8%A3%E0%B9%88%E0%B8%87%E0%B9%81
      %E0%B8%AA%E0%B8%87%E0%B9%81%E0%B8%A5%E0%B8%B0
      %E0%B9%81%E0%B8%9C%E0%B9%88%E0%B8%99%E0%B9%82
      %E0%B8%9B%E0%B8%A3%E0%B9%88%E0%B8%87%E0%B9%81
      %E0%B8%AA%E0%B8%87
    
  ceramic:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9A
      %E0%B8%B7%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%AB
      %E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%84%E0%B8%B2
      %E0%B9%80%E0%B8%8B%E0%B8%A3%E0%B8%B2%E0%B8%A1
      %E0%B8%B4%E0%B8%81

  concrete:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9A
      %E0%B8%B7%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%AB
      %E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%84%E0%B8%B2
      %E0%B8%84%E0%B8%AD%E0%B8%99%E0%B8%81%E0%B8%A3
      %E0%B8%B5%E0%B8%95
  
  fiber_cement:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%9A
      %E0%B8%B7%E0%B9%89%E0%B8%AD%E0%B8%87%E0%B8%AB
      %E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%84%E0%B8%B2
      %E0%B9%84%E0%B8%9F%E0%B9%80%E0%B8%9A%E0%B8%AD
      %E0%B8%A3%E0%B9%8C%E0%B8%8B%E0%B8%B5%E0%B9%80
      %E0%B8%A1%E0%B8%99%E0%B8%95%E0%B9%8C
  
  ventilation:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%8A%E0%B8%B8%E0%B8%94%E0%B8%81%E0%B8%A3
      %E0%B8%B0%E0%B9%80%E0%B8%9A%E0%B8%B7%E0%B9%89
      %E0%B8%AD%E0%B8%87%E0%B8%A3%E0%B8%B0%E0%B8%9A
      %E0%B8%B2%E0%B8%A2%E0%B8%AD%E0%B8%B2%E0%B8%81
      %E0%B8%B2%E0%B8%A8

  metal_sheet:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%AB%E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%84
      %E0%B8%B2%E0%B9%80%E0%B8%A1%E0%B8%97%E0%B8%B1
      %E0%B8%A5%E0%B8%8A%E0%B8%B5%E0%B8%97
  
  roofing_equipment:
    <<: *roof_tile_default
    web_url: |
      https://www.scghome.com/products/subcategory/
      %E0%B8%AD%E0%B8%B8%E0%B8%9B%E0%B8%81%E0%B8%A3
      %E0%B8%93%E0%B9%8C%E0%B8%95%E0%B8%B4%E0%B8%94
      %E0%B8%95%E0%B8%B1%E0%B9%89%E0%B8%87%E0%B8%AB
      %E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%84%E0%B8%B2




  
